### ISSUE TITLE
Wiki document Installation portion updates

### ISSUE THREAD

**Issue by luckypig3400** [Chinlinlee/raccoon-dicom#8]
Dear @Chinlinlee ,

I hope this message finds you well. 😄 I wanted to inform you that I have made some edits to the installation guide for [this project's Wiki](https://github.com/Chinlinlee/raccoon-dicom/wiki/Installation). These updates aim to improve the clarity and accuracy of the instructions, making it easier for new users to get started with the project.

As an active contributor and user of your project, I understand the importance of a comprehensive and user-friendly installation guide. I took the initiative to review the existing documentation and make the necessary changes to ensure that users have a smooth and hassle-free experience during the installation process.

To make it convenient for you to review the updates, I have cloned the Wiki page locally and modified the installation guide. You can access the edited document at [LuckyPig-modified@20230522_raccoon-dicom.wiki.zip](https://github.com/Chinlinlee/raccoon-dicom/files/11529377/raccoon-dicom.wiki.zip).
The following image included a summary of the changes I made:
![image](https://github.com/Chinlinlee/raccoon-dicom/assets/25383278/09d0bf70-a88c-43e9-bc9e-0202c41fa0f8)

I value your expertise and insights as the author of the project, and I would greatly appreciate your feedback on the updated installation guide. Your review will help ensure that the instructions are accurate and easily understandable for all users. If you have any questions or need further information regarding the changes I made, please feel free to reach out to me.😸   I'm more than happy to provide any additional clarification or assistance you may require.

Thank you for your time and consideration. Your efforts in maintaining and improving the [raccoon-dicom](https://github.com/Chinlinlee/raccoon-dicom) are greatly appreciated. 🎉 
I look forward to your feedback on the updated installation guide, and I'm excited about the opportunity to contribute further to this wonderful project.

Best regards,
LuckyPig

**Comment by Chinlinlee** [comment]
Thank you for your contribution.
The information has been updated in the wiki.
- Furthermore, I have removed the information regarding Windows JDK >= 17 as I have tested and confirmed that work fine on JDK 11 as shown in the figure following
![image](https://github.com/Chinlinlee/raccoon-dicom/assets/49154622/726688a8-aeb6-4030-a4d9-f94f66c3c5b8)

**Comment by luckypig3400** [comment]
## Thanks a lot for telling me that JDK 11 works properly with this project. 👍 

### I have also tested with [Open JDK 11.0.19](https://www.openlogic.com/openjdk-downloads?field_java_parent_version_target_id=406&field_operating_system_target_id=436&field_architecture_target_id=All&field_java_package_target_id=396), and it works pretty well! 😃 
![image](https://github.com/Chinlinlee/raccoon-dicom/assets/25383278/cb020960-9442-4f00-83eb-2e333b89c024)

![image](https://github.com/Chinlinlee/raccoon-dicom/assets/25383278/81d4c7f9-bb26-426f-9e52-4bb5bf625b6e)

### ⚠️  It only seems to be the issue with [Oracle JDK 11](https://www.oracle.com/java/technologies/javase/jdk11-archive-downloads.html)
![image](https://github.com/Chinlinlee/raccoon-dicom/assets/25383278/954ae838-7b0d-4672-9bc3-043949f4566c)
